/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface SwitchMaterial {
        "disabled": boolean;
        "switch": string;
        "theme": string;
    }
}
export interface SwitchMaterialCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSwitchMaterialElement;
}
declare global {
    interface HTMLSwitchMaterialElement extends Components.SwitchMaterial, HTMLStencilElement {
    }
    var HTMLSwitchMaterialElement: {
        prototype: HTMLSwitchMaterialElement;
        new (): HTMLSwitchMaterialElement;
    };
    interface HTMLElementTagNameMap {
        "switch-material": HTMLSwitchMaterialElement;
    }
}
declare namespace LocalJSX {
    interface SwitchMaterial {
        "disabled"?: boolean;
        "onSwitch"?: (event: SwitchMaterialCustomEvent<object>) => void;
        "switch"?: string;
        "theme"?: string;
    }
    interface IntrinsicElements {
        "switch-material": SwitchMaterial;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "switch-material": LocalJSX.SwitchMaterial & JSXBase.HTMLAttributes<HTMLSwitchMaterialElement>;
        }
    }
}
