/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface ToggleSwitch {
        "disabled": boolean;
        "switch": string;
    }
}
export interface ToggleSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLToggleSwitchElement;
}
declare global {
    interface HTMLToggleSwitchElement extends Components.ToggleSwitch, HTMLStencilElement {
    }
    var HTMLToggleSwitchElement: {
        prototype: HTMLToggleSwitchElement;
        new (): HTMLToggleSwitchElement;
    };
    interface HTMLElementTagNameMap {
        "toggle-switch": HTMLToggleSwitchElement;
    }
}
declare namespace LocalJSX {
    interface ToggleSwitch {
        "disabled"?: boolean;
        "onSwitch"?: (event: ToggleSwitchCustomEvent<object>) => void;
        "switch"?: string;
    }
    interface IntrinsicElements {
        "toggle-switch": ToggleSwitch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "toggle-switch": LocalJSX.ToggleSwitch & JSXBase.HTMLAttributes<HTMLToggleSwitchElement>;
        }
    }
}
