/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface LinkCssEight {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface LinkCssFive {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface LinkCssFour {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface LinkCssNine {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface LinkCssOne {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface LinkCssSeven {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface LinkCssSix {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface LinkCssThree {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface LinkCssTwo {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface MafanfaLink {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
}
export interface LinkCssEightCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLinkCssEightElement;
}
export interface LinkCssFiveCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLinkCssFiveElement;
}
export interface LinkCssFourCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLinkCssFourElement;
}
export interface LinkCssNineCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLinkCssNineElement;
}
export interface LinkCssOneCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLinkCssOneElement;
}
export interface LinkCssSevenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLinkCssSevenElement;
}
export interface LinkCssSixCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLinkCssSixElement;
}
export interface LinkCssThreeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLinkCssThreeElement;
}
export interface LinkCssTwoCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLinkCssTwoElement;
}
export interface MafanfaLinkCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMafanfaLinkElement;
}
declare global {
    interface HTMLLinkCssEightElement extends Components.LinkCssEight, HTMLStencilElement {
    }
    var HTMLLinkCssEightElement: {
        prototype: HTMLLinkCssEightElement;
        new (): HTMLLinkCssEightElement;
    };
    interface HTMLLinkCssFiveElement extends Components.LinkCssFive, HTMLStencilElement {
    }
    var HTMLLinkCssFiveElement: {
        prototype: HTMLLinkCssFiveElement;
        new (): HTMLLinkCssFiveElement;
    };
    interface HTMLLinkCssFourElement extends Components.LinkCssFour, HTMLStencilElement {
    }
    var HTMLLinkCssFourElement: {
        prototype: HTMLLinkCssFourElement;
        new (): HTMLLinkCssFourElement;
    };
    interface HTMLLinkCssNineElement extends Components.LinkCssNine, HTMLStencilElement {
    }
    var HTMLLinkCssNineElement: {
        prototype: HTMLLinkCssNineElement;
        new (): HTMLLinkCssNineElement;
    };
    interface HTMLLinkCssOneElement extends Components.LinkCssOne, HTMLStencilElement {
    }
    var HTMLLinkCssOneElement: {
        prototype: HTMLLinkCssOneElement;
        new (): HTMLLinkCssOneElement;
    };
    interface HTMLLinkCssSevenElement extends Components.LinkCssSeven, HTMLStencilElement {
    }
    var HTMLLinkCssSevenElement: {
        prototype: HTMLLinkCssSevenElement;
        new (): HTMLLinkCssSevenElement;
    };
    interface HTMLLinkCssSixElement extends Components.LinkCssSix, HTMLStencilElement {
    }
    var HTMLLinkCssSixElement: {
        prototype: HTMLLinkCssSixElement;
        new (): HTMLLinkCssSixElement;
    };
    interface HTMLLinkCssThreeElement extends Components.LinkCssThree, HTMLStencilElement {
    }
    var HTMLLinkCssThreeElement: {
        prototype: HTMLLinkCssThreeElement;
        new (): HTMLLinkCssThreeElement;
    };
    interface HTMLLinkCssTwoElement extends Components.LinkCssTwo, HTMLStencilElement {
    }
    var HTMLLinkCssTwoElement: {
        prototype: HTMLLinkCssTwoElement;
        new (): HTMLLinkCssTwoElement;
    };
    interface HTMLMafanfaLinkElement extends Components.MafanfaLink, HTMLStencilElement {
    }
    var HTMLMafanfaLinkElement: {
        prototype: HTMLMafanfaLinkElement;
        new (): HTMLMafanfaLinkElement;
    };
    interface HTMLElementTagNameMap {
        "link-css-eight": HTMLLinkCssEightElement;
        "link-css-five": HTMLLinkCssFiveElement;
        "link-css-four": HTMLLinkCssFourElement;
        "link-css-nine": HTMLLinkCssNineElement;
        "link-css-one": HTMLLinkCssOneElement;
        "link-css-seven": HTMLLinkCssSevenElement;
        "link-css-six": HTMLLinkCssSixElement;
        "link-css-three": HTMLLinkCssThreeElement;
        "link-css-two": HTMLLinkCssTwoElement;
        "mafanfa-link": HTMLMafanfaLinkElement;
    }
}
declare namespace LocalJSX {
    interface LinkCssEight {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: LinkCssEightCustomEvent<string>) => void;
    }
    interface LinkCssFive {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: LinkCssFiveCustomEvent<string>) => void;
    }
    interface LinkCssFour {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: LinkCssFourCustomEvent<string>) => void;
    }
    interface LinkCssNine {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: LinkCssNineCustomEvent<string>) => void;
    }
    interface LinkCssOne {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: LinkCssOneCustomEvent<string>) => void;
    }
    interface LinkCssSeven {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: LinkCssSevenCustomEvent<string>) => void;
    }
    interface LinkCssSix {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: LinkCssSixCustomEvent<string>) => void;
    }
    interface LinkCssThree {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: LinkCssThreeCustomEvent<string>) => void;
    }
    interface LinkCssTwo {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: LinkCssTwoCustomEvent<string>) => void;
    }
    interface MafanfaLink {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: MafanfaLinkCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "link-css-eight": LinkCssEight;
        "link-css-five": LinkCssFive;
        "link-css-four": LinkCssFour;
        "link-css-nine": LinkCssNine;
        "link-css-one": LinkCssOne;
        "link-css-seven": LinkCssSeven;
        "link-css-six": LinkCssSix;
        "link-css-three": LinkCssThree;
        "link-css-two": LinkCssTwo;
        "mafanfa-link": MafanfaLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "link-css-eight": LocalJSX.LinkCssEight & JSXBase.HTMLAttributes<HTMLLinkCssEightElement>;
            "link-css-five": LocalJSX.LinkCssFive & JSXBase.HTMLAttributes<HTMLLinkCssFiveElement>;
            "link-css-four": LocalJSX.LinkCssFour & JSXBase.HTMLAttributes<HTMLLinkCssFourElement>;
            "link-css-nine": LocalJSX.LinkCssNine & JSXBase.HTMLAttributes<HTMLLinkCssNineElement>;
            "link-css-one": LocalJSX.LinkCssOne & JSXBase.HTMLAttributes<HTMLLinkCssOneElement>;
            "link-css-seven": LocalJSX.LinkCssSeven & JSXBase.HTMLAttributes<HTMLLinkCssSevenElement>;
            "link-css-six": LocalJSX.LinkCssSix & JSXBase.HTMLAttributes<HTMLLinkCssSixElement>;
            "link-css-three": LocalJSX.LinkCssThree & JSXBase.HTMLAttributes<HTMLLinkCssThreeElement>;
            "link-css-two": LocalJSX.LinkCssTwo & JSXBase.HTMLAttributes<HTMLLinkCssTwoElement>;
            "mafanfa-link": LocalJSX.MafanfaLink & JSXBase.HTMLAttributes<HTMLMafanfaLinkElement>;
        }
    }
}
