/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface ButtonCssEight {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssEleven {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssFifteen {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssFive {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssFour {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssFourteen {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssMafanfa {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssNine {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssOne {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssSeven {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssSix {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssSixteen {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssTen {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssThirteen {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssThree {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssTwelve {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssTwo {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ButtonCssWave {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface IgniteButtonCss {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface IgniteButtonJs {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface MagnetButton {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface PaxCssButton {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface PaxJsButton {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface PaxJsButtonVariantOne {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface PaxJsButtonVariantTwo {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface SendPotionButton {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
    interface ZoryButton {
        "cssSource": string;
        "htmlSource": string;
        "jsSource": string;
    }
}
export interface ButtonCssEightCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssEightElement;
}
export interface ButtonCssElevenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssElevenElement;
}
export interface ButtonCssFifteenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssFifteenElement;
}
export interface ButtonCssFiveCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssFiveElement;
}
export interface ButtonCssFourCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssFourElement;
}
export interface ButtonCssFourteenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssFourteenElement;
}
export interface ButtonCssMafanfaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssMafanfaElement;
}
export interface ButtonCssNineCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssNineElement;
}
export interface ButtonCssOneCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssOneElement;
}
export interface ButtonCssSevenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssSevenElement;
}
export interface ButtonCssSixCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssSixElement;
}
export interface ButtonCssSixteenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssSixteenElement;
}
export interface ButtonCssTenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssTenElement;
}
export interface ButtonCssThirteenCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssThirteenElement;
}
export interface ButtonCssThreeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssThreeElement;
}
export interface ButtonCssTwelveCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssTwelveElement;
}
export interface ButtonCssTwoCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssTwoElement;
}
export interface ButtonCssWaveCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonCssWaveElement;
}
export interface IgniteButtonCssCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIgniteButtonCssElement;
}
export interface IgniteButtonJsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIgniteButtonJsElement;
}
export interface MagnetButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMagnetButtonElement;
}
export interface PaxCssButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPaxCssButtonElement;
}
export interface PaxJsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPaxJsButtonElement;
}
export interface PaxJsButtonVariantOneCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPaxJsButtonVariantOneElement;
}
export interface PaxJsButtonVariantTwoCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPaxJsButtonVariantTwoElement;
}
export interface SendPotionButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSendPotionButtonElement;
}
export interface ZoryButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLZoryButtonElement;
}
declare global {
    interface HTMLButtonCssEightElement extends Components.ButtonCssEight, HTMLStencilElement {
    }
    var HTMLButtonCssEightElement: {
        prototype: HTMLButtonCssEightElement;
        new (): HTMLButtonCssEightElement;
    };
    interface HTMLButtonCssElevenElement extends Components.ButtonCssEleven, HTMLStencilElement {
    }
    var HTMLButtonCssElevenElement: {
        prototype: HTMLButtonCssElevenElement;
        new (): HTMLButtonCssElevenElement;
    };
    interface HTMLButtonCssFifteenElement extends Components.ButtonCssFifteen, HTMLStencilElement {
    }
    var HTMLButtonCssFifteenElement: {
        prototype: HTMLButtonCssFifteenElement;
        new (): HTMLButtonCssFifteenElement;
    };
    interface HTMLButtonCssFiveElement extends Components.ButtonCssFive, HTMLStencilElement {
    }
    var HTMLButtonCssFiveElement: {
        prototype: HTMLButtonCssFiveElement;
        new (): HTMLButtonCssFiveElement;
    };
    interface HTMLButtonCssFourElement extends Components.ButtonCssFour, HTMLStencilElement {
    }
    var HTMLButtonCssFourElement: {
        prototype: HTMLButtonCssFourElement;
        new (): HTMLButtonCssFourElement;
    };
    interface HTMLButtonCssFourteenElement extends Components.ButtonCssFourteen, HTMLStencilElement {
    }
    var HTMLButtonCssFourteenElement: {
        prototype: HTMLButtonCssFourteenElement;
        new (): HTMLButtonCssFourteenElement;
    };
    interface HTMLButtonCssMafanfaElement extends Components.ButtonCssMafanfa, HTMLStencilElement {
    }
    var HTMLButtonCssMafanfaElement: {
        prototype: HTMLButtonCssMafanfaElement;
        new (): HTMLButtonCssMafanfaElement;
    };
    interface HTMLButtonCssNineElement extends Components.ButtonCssNine, HTMLStencilElement {
    }
    var HTMLButtonCssNineElement: {
        prototype: HTMLButtonCssNineElement;
        new (): HTMLButtonCssNineElement;
    };
    interface HTMLButtonCssOneElement extends Components.ButtonCssOne, HTMLStencilElement {
    }
    var HTMLButtonCssOneElement: {
        prototype: HTMLButtonCssOneElement;
        new (): HTMLButtonCssOneElement;
    };
    interface HTMLButtonCssSevenElement extends Components.ButtonCssSeven, HTMLStencilElement {
    }
    var HTMLButtonCssSevenElement: {
        prototype: HTMLButtonCssSevenElement;
        new (): HTMLButtonCssSevenElement;
    };
    interface HTMLButtonCssSixElement extends Components.ButtonCssSix, HTMLStencilElement {
    }
    var HTMLButtonCssSixElement: {
        prototype: HTMLButtonCssSixElement;
        new (): HTMLButtonCssSixElement;
    };
    interface HTMLButtonCssSixteenElement extends Components.ButtonCssSixteen, HTMLStencilElement {
    }
    var HTMLButtonCssSixteenElement: {
        prototype: HTMLButtonCssSixteenElement;
        new (): HTMLButtonCssSixteenElement;
    };
    interface HTMLButtonCssTenElement extends Components.ButtonCssTen, HTMLStencilElement {
    }
    var HTMLButtonCssTenElement: {
        prototype: HTMLButtonCssTenElement;
        new (): HTMLButtonCssTenElement;
    };
    interface HTMLButtonCssThirteenElement extends Components.ButtonCssThirteen, HTMLStencilElement {
    }
    var HTMLButtonCssThirteenElement: {
        prototype: HTMLButtonCssThirteenElement;
        new (): HTMLButtonCssThirteenElement;
    };
    interface HTMLButtonCssThreeElement extends Components.ButtonCssThree, HTMLStencilElement {
    }
    var HTMLButtonCssThreeElement: {
        prototype: HTMLButtonCssThreeElement;
        new (): HTMLButtonCssThreeElement;
    };
    interface HTMLButtonCssTwelveElement extends Components.ButtonCssTwelve, HTMLStencilElement {
    }
    var HTMLButtonCssTwelveElement: {
        prototype: HTMLButtonCssTwelveElement;
        new (): HTMLButtonCssTwelveElement;
    };
    interface HTMLButtonCssTwoElement extends Components.ButtonCssTwo, HTMLStencilElement {
    }
    var HTMLButtonCssTwoElement: {
        prototype: HTMLButtonCssTwoElement;
        new (): HTMLButtonCssTwoElement;
    };
    interface HTMLButtonCssWaveElement extends Components.ButtonCssWave, HTMLStencilElement {
    }
    var HTMLButtonCssWaveElement: {
        prototype: HTMLButtonCssWaveElement;
        new (): HTMLButtonCssWaveElement;
    };
    interface HTMLIgniteButtonCssElement extends Components.IgniteButtonCss, HTMLStencilElement {
    }
    var HTMLIgniteButtonCssElement: {
        prototype: HTMLIgniteButtonCssElement;
        new (): HTMLIgniteButtonCssElement;
    };
    interface HTMLIgniteButtonJsElement extends Components.IgniteButtonJs, HTMLStencilElement {
    }
    var HTMLIgniteButtonJsElement: {
        prototype: HTMLIgniteButtonJsElement;
        new (): HTMLIgniteButtonJsElement;
    };
    interface HTMLMagnetButtonElement extends Components.MagnetButton, HTMLStencilElement {
    }
    var HTMLMagnetButtonElement: {
        prototype: HTMLMagnetButtonElement;
        new (): HTMLMagnetButtonElement;
    };
    interface HTMLPaxCssButtonElement extends Components.PaxCssButton, HTMLStencilElement {
    }
    var HTMLPaxCssButtonElement: {
        prototype: HTMLPaxCssButtonElement;
        new (): HTMLPaxCssButtonElement;
    };
    interface HTMLPaxJsButtonElement extends Components.PaxJsButton, HTMLStencilElement {
    }
    var HTMLPaxJsButtonElement: {
        prototype: HTMLPaxJsButtonElement;
        new (): HTMLPaxJsButtonElement;
    };
    interface HTMLPaxJsButtonVariantOneElement extends Components.PaxJsButtonVariantOne, HTMLStencilElement {
    }
    var HTMLPaxJsButtonVariantOneElement: {
        prototype: HTMLPaxJsButtonVariantOneElement;
        new (): HTMLPaxJsButtonVariantOneElement;
    };
    interface HTMLPaxJsButtonVariantTwoElement extends Components.PaxJsButtonVariantTwo, HTMLStencilElement {
    }
    var HTMLPaxJsButtonVariantTwoElement: {
        prototype: HTMLPaxJsButtonVariantTwoElement;
        new (): HTMLPaxJsButtonVariantTwoElement;
    };
    interface HTMLSendPotionButtonElement extends Components.SendPotionButton, HTMLStencilElement {
    }
    var HTMLSendPotionButtonElement: {
        prototype: HTMLSendPotionButtonElement;
        new (): HTMLSendPotionButtonElement;
    };
    interface HTMLZoryButtonElement extends Components.ZoryButton, HTMLStencilElement {
    }
    var HTMLZoryButtonElement: {
        prototype: HTMLZoryButtonElement;
        new (): HTMLZoryButtonElement;
    };
    interface HTMLElementTagNameMap {
        "button-css-eight": HTMLButtonCssEightElement;
        "button-css-eleven": HTMLButtonCssElevenElement;
        "button-css-fifteen": HTMLButtonCssFifteenElement;
        "button-css-five": HTMLButtonCssFiveElement;
        "button-css-four": HTMLButtonCssFourElement;
        "button-css-fourteen": HTMLButtonCssFourteenElement;
        "button-css-mafanfa": HTMLButtonCssMafanfaElement;
        "button-css-nine": HTMLButtonCssNineElement;
        "button-css-one": HTMLButtonCssOneElement;
        "button-css-seven": HTMLButtonCssSevenElement;
        "button-css-six": HTMLButtonCssSixElement;
        "button-css-sixteen": HTMLButtonCssSixteenElement;
        "button-css-ten": HTMLButtonCssTenElement;
        "button-css-thirteen": HTMLButtonCssThirteenElement;
        "button-css-three": HTMLButtonCssThreeElement;
        "button-css-twelve": HTMLButtonCssTwelveElement;
        "button-css-two": HTMLButtonCssTwoElement;
        "button-css-wave": HTMLButtonCssWaveElement;
        "ignite-button-css": HTMLIgniteButtonCssElement;
        "ignite-button-js": HTMLIgniteButtonJsElement;
        "magnet-button": HTMLMagnetButtonElement;
        "pax-css-button": HTMLPaxCssButtonElement;
        "pax-js-button": HTMLPaxJsButtonElement;
        "pax-js-button-variant-one": HTMLPaxJsButtonVariantOneElement;
        "pax-js-button-variant-two": HTMLPaxJsButtonVariantTwoElement;
        "send-potion-button": HTMLSendPotionButtonElement;
        "zory-button": HTMLZoryButtonElement;
    }
}
declare namespace LocalJSX {
    interface ButtonCssEight {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssEightCustomEvent<string>) => void;
    }
    interface ButtonCssEleven {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssElevenCustomEvent<string>) => void;
    }
    interface ButtonCssFifteen {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssFifteenCustomEvent<string>) => void;
    }
    interface ButtonCssFive {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssFiveCustomEvent<string>) => void;
    }
    interface ButtonCssFour {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssFourCustomEvent<string>) => void;
    }
    interface ButtonCssFourteen {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssFourteenCustomEvent<string>) => void;
    }
    interface ButtonCssMafanfa {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssMafanfaCustomEvent<string>) => void;
    }
    interface ButtonCssNine {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssNineCustomEvent<string>) => void;
    }
    interface ButtonCssOne {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssOneCustomEvent<string>) => void;
    }
    interface ButtonCssSeven {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssSevenCustomEvent<string>) => void;
    }
    interface ButtonCssSix {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssSixCustomEvent<string>) => void;
    }
    interface ButtonCssSixteen {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssSixteenCustomEvent<string>) => void;
    }
    interface ButtonCssTen {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssTenCustomEvent<string>) => void;
    }
    interface ButtonCssThirteen {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssThirteenCustomEvent<string>) => void;
    }
    interface ButtonCssThree {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssThreeCustomEvent<string>) => void;
    }
    interface ButtonCssTwelve {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssTwelveCustomEvent<string>) => void;
    }
    interface ButtonCssTwo {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssTwoCustomEvent<string>) => void;
    }
    interface ButtonCssWave {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ButtonCssWaveCustomEvent<string>) => void;
    }
    interface IgniteButtonCss {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: IgniteButtonCssCustomEvent<string>) => void;
    }
    interface IgniteButtonJs {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: IgniteButtonJsCustomEvent<string>) => void;
    }
    interface MagnetButton {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: MagnetButtonCustomEvent<string>) => void;
    }
    interface PaxCssButton {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: PaxCssButtonCustomEvent<string>) => void;
    }
    interface PaxJsButton {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: PaxJsButtonCustomEvent<string>) => void;
    }
    interface PaxJsButtonVariantOne {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: PaxJsButtonVariantOneCustomEvent<string>) => void;
    }
    interface PaxJsButtonVariantTwo {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: PaxJsButtonVariantTwoCustomEvent<string>) => void;
    }
    interface SendPotionButton {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: SendPotionButtonCustomEvent<string>) => void;
    }
    interface ZoryButton {
        "cssSource"?: string;
        "htmlSource"?: string;
        "jsSource"?: string;
        "onHighlightCode"?: (event: ZoryButtonCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "button-css-eight": ButtonCssEight;
        "button-css-eleven": ButtonCssEleven;
        "button-css-fifteen": ButtonCssFifteen;
        "button-css-five": ButtonCssFive;
        "button-css-four": ButtonCssFour;
        "button-css-fourteen": ButtonCssFourteen;
        "button-css-mafanfa": ButtonCssMafanfa;
        "button-css-nine": ButtonCssNine;
        "button-css-one": ButtonCssOne;
        "button-css-seven": ButtonCssSeven;
        "button-css-six": ButtonCssSix;
        "button-css-sixteen": ButtonCssSixteen;
        "button-css-ten": ButtonCssTen;
        "button-css-thirteen": ButtonCssThirteen;
        "button-css-three": ButtonCssThree;
        "button-css-twelve": ButtonCssTwelve;
        "button-css-two": ButtonCssTwo;
        "button-css-wave": ButtonCssWave;
        "ignite-button-css": IgniteButtonCss;
        "ignite-button-js": IgniteButtonJs;
        "magnet-button": MagnetButton;
        "pax-css-button": PaxCssButton;
        "pax-js-button": PaxJsButton;
        "pax-js-button-variant-one": PaxJsButtonVariantOne;
        "pax-js-button-variant-two": PaxJsButtonVariantTwo;
        "send-potion-button": SendPotionButton;
        "zory-button": ZoryButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-css-eight": LocalJSX.ButtonCssEight & JSXBase.HTMLAttributes<HTMLButtonCssEightElement>;
            "button-css-eleven": LocalJSX.ButtonCssEleven & JSXBase.HTMLAttributes<HTMLButtonCssElevenElement>;
            "button-css-fifteen": LocalJSX.ButtonCssFifteen & JSXBase.HTMLAttributes<HTMLButtonCssFifteenElement>;
            "button-css-five": LocalJSX.ButtonCssFive & JSXBase.HTMLAttributes<HTMLButtonCssFiveElement>;
            "button-css-four": LocalJSX.ButtonCssFour & JSXBase.HTMLAttributes<HTMLButtonCssFourElement>;
            "button-css-fourteen": LocalJSX.ButtonCssFourteen & JSXBase.HTMLAttributes<HTMLButtonCssFourteenElement>;
            "button-css-mafanfa": LocalJSX.ButtonCssMafanfa & JSXBase.HTMLAttributes<HTMLButtonCssMafanfaElement>;
            "button-css-nine": LocalJSX.ButtonCssNine & JSXBase.HTMLAttributes<HTMLButtonCssNineElement>;
            "button-css-one": LocalJSX.ButtonCssOne & JSXBase.HTMLAttributes<HTMLButtonCssOneElement>;
            "button-css-seven": LocalJSX.ButtonCssSeven & JSXBase.HTMLAttributes<HTMLButtonCssSevenElement>;
            "button-css-six": LocalJSX.ButtonCssSix & JSXBase.HTMLAttributes<HTMLButtonCssSixElement>;
            "button-css-sixteen": LocalJSX.ButtonCssSixteen & JSXBase.HTMLAttributes<HTMLButtonCssSixteenElement>;
            "button-css-ten": LocalJSX.ButtonCssTen & JSXBase.HTMLAttributes<HTMLButtonCssTenElement>;
            "button-css-thirteen": LocalJSX.ButtonCssThirteen & JSXBase.HTMLAttributes<HTMLButtonCssThirteenElement>;
            "button-css-three": LocalJSX.ButtonCssThree & JSXBase.HTMLAttributes<HTMLButtonCssThreeElement>;
            "button-css-twelve": LocalJSX.ButtonCssTwelve & JSXBase.HTMLAttributes<HTMLButtonCssTwelveElement>;
            "button-css-two": LocalJSX.ButtonCssTwo & JSXBase.HTMLAttributes<HTMLButtonCssTwoElement>;
            "button-css-wave": LocalJSX.ButtonCssWave & JSXBase.HTMLAttributes<HTMLButtonCssWaveElement>;
            "ignite-button-css": LocalJSX.IgniteButtonCss & JSXBase.HTMLAttributes<HTMLIgniteButtonCssElement>;
            "ignite-button-js": LocalJSX.IgniteButtonJs & JSXBase.HTMLAttributes<HTMLIgniteButtonJsElement>;
            "magnet-button": LocalJSX.MagnetButton & JSXBase.HTMLAttributes<HTMLMagnetButtonElement>;
            "pax-css-button": LocalJSX.PaxCssButton & JSXBase.HTMLAttributes<HTMLPaxCssButtonElement>;
            "pax-js-button": LocalJSX.PaxJsButton & JSXBase.HTMLAttributes<HTMLPaxJsButtonElement>;
            "pax-js-button-variant-one": LocalJSX.PaxJsButtonVariantOne & JSXBase.HTMLAttributes<HTMLPaxJsButtonVariantOneElement>;
            "pax-js-button-variant-two": LocalJSX.PaxJsButtonVariantTwo & JSXBase.HTMLAttributes<HTMLPaxJsButtonVariantTwoElement>;
            "send-potion-button": LocalJSX.SendPotionButton & JSXBase.HTMLAttributes<HTMLSendPotionButtonElement>;
            "zory-button": LocalJSX.ZoryButton & JSXBase.HTMLAttributes<HTMLZoryButtonElement>;
        }
    }
}
